nick: Sekvenssi

admins:
  - 'huqa!huqa@silokki.org'
  - 'huqa!~huqa@silokki.org'

networks:
  IRCnet:
    server: irc.elisa.fi
    channels:
      - '#suur-kaleva'
      - '#fam'
      - '#neo-kaleva'
      - '#kutsut'
      - '#avaruusrosvo'
      - '#testkanv'
      - '#ptestkanv'
    ignored_nicks:
      - 'hikku-p'
      - 'iskender'
      - 'lfo_to_cutoff'
      - 'lfo_to_pitch'
      - 'urli'
    linerate: 2
